In [1]:
# Import the Pandas library
import pandas as pd

In [2]:
# Create a reference the CSV file desired
csv_path = "Resources/ufoSightings.csv"

# Read the CSV into a Pandas DataFrame
ufo_df = pd.read_csv(csv_path)

# Print the first five rows of data to the screen
ufo_df.head()

/Users/Ronessa/anaconda/envs/PythonData/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [3]:
# Check to see if there are any rows with missing data
ufo_df.count()

datetime                80332
city                    80332
state                   74535
country                 70662
shape                   78400
duration (seconds)      80332
duration (hours/min)    80332
comments                80317
date posted             80332
latitude                80332
longitude               80332
dtype: int64

In [4]:
# Remove the rows with missing data
clean_ufo_df = ufo_df.dropna(how="any")
clean_ufo_df.count()

datetime                66516
city                    66516
state                   66516
country                 66516
shape                   66516
duration (seconds)      66516
duration (hours/min)    66516
comments                66516
date posted             66516
latitude                66516
longitude               66516
dtype: int64

In [5]:
# Filter the data so that only those sightings in the US are in a DataFrame
usa_ufo_df = clean_ufo_df.loc[clean_ufo_df["country"] == "us", :]
usa_ufo_df

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595,-82.188889
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.1175,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.5861111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.2947222,-82.984167
10,10/10/1968 13:00,hawthorne,ca,us,circle,300,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,10/31/2003,33.9163889,-118.351667
11,10/10/1968 19:00,brevard,nc,us,fireball,180,3 minutes,silent red /orange mass of energy floated by t...,6/12/2008,35.2333333,-82.734444
12,10/10/1970 16:00,bellmore,ny,us,disk,1800,30 min.,silver disc seen by family and neighbors,5/11/2000,40.6686111,-73.527500
13,10/10/1970 19:00,manchester,ky,us,unknown,180,3 minutes,Slow moving&#44 silent craft accelerated at an...,2/14/2008,37.1536111,-83.761944
14,10/10/1971 21:00,lexington,nc,us,oval,30,30 seconds,green oval shaped light over my local church&#...,2/14/2010,35.8238889,-80.253611
15,10/10/1972 19:00,harlan county,ky,us,circle,1200,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,9/15/2005,36.8430556,-83.321944
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120,2 minutes,The UFO was so close&#44 my battery in the car...,8/14/2007,42.5377778,-83.233056
17,10/10/1973 19:00,niantic,ct,us,disk,1800,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,9/24/2003,41.3252778,-72.193611
19,10/10/1974 19:30,hudson,ma,us,other,2700,45 minutes,Not sure of the eact month or year of this sig...,8/10/1999,42.3916667,-71.566667
21,10/10/1974 23:00,hudson,ks,us,light,1200,one hour?,The light chased us.,7/25/2004,38.1055556,-98.659722
22,10/10/1975 17:00,north charleston,sc,us,light,360,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2/14/2008,32.8544444,-79.975000
23,10/10/1976 20:30,washougal,wa,us,oval,60,1 minute,Three extremely large lights hanging above nea...,2/7/2014,45.5827778,-122.352222
25,10/10/1977 12:00,san antonio,tx,us,other,30,30 seconds,i was about six or seven and my family and me ...,2/24/2005,29.4238889,-98.493333
26,10/10/1977 22:00,louisville,ky,us,light,30,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,3/17/2004,38.2541667,-85.759444
27,10/10/1978 2:00,elmont,ny,us,rectangle,300,5min,A memory I will never forget that happened men...,2/1/2007,40.7008333,-73.713333
28,10/10/1979 0:00,poughkeepsie,ny,us,chevron,900,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,4/16/2005,41.7002778,-73.921389
30,10/10/1979 22:00,san diego,ca,us,oval,180,3 minutes,My 2nd UFO sighting&#44 October 1979,8/5/2001,32.7152778,-117.156389
31,10/10/1979 22:00,security,co,us,unknown,1800,30mins.,very low clouds all different colors&#44search...,1/28/1999,38.7583333,-104.742500
32,10/10/1980 19:00,houston,tx,us,sphere,180,3 min,Sphere&#44 No lights&#44 moving through neigh...,4/16/2005,29.7630556,-95.363056
33,10/10/1980 22:00,dallas,tx,us,unknown,300,5 minutes,Strange shape shifting craft of pure light ene...,10/28/2002,32.7833333,-96.800000
34,10/10/1980 23:30,manchester,nh,us,light,300,3 to 5 min,A red glowing sphere stopped and watched me.,11/21/2010,42.9955556,-71.455278
36,10/10/1984 5:00,houston,tx,us,circle,60,1 minute,2 experience with unkown,4/18/2012,29.7630556,-95.363056
37,10/10/1984 12:00,traverse city,mi,us,other,120,couple minutes,translucent football seen over city airport,10/7/2003,44.7630556,-85.620556
...,...,...,...,...,...,...,...,...,...,...,...
80297,9/9/2012 17:00,belton,mo,us,circle,90,90 seconds,Orange ball steady on the horizon&#44 Belton&#...,9/24/2012,38.8119,-94.531667
80298,9/9/2012 19:05,jackson,tn,us,fireball,600,10 minutes,Two fire balls in Jackson&#44 TN,9/24/2012,35.6144,-88.813889
80299,9/9/2012 20:00,arcata,ca,us,formation,600,10 minutes,Object with red and green lights moving sited ...,9/24/2012,40.8667,-124.081667
80300,9/9/2012 20:00,kannapolis,nc,us,fireball,300,5 minutes,Fireball traveling in the sky,9/24/2012,35.4872,-80.621944
80301,9/9/2012 20:00,murfreesboro,tn,us,sphere,180,3 minutes,6 red sphere shaped UFOs formed a pair of tria...,9/24/2012,35.8456,-86.390278
80302,9/9/2012 20:00,wilson,nc,us,light,10800,3 hours,Bright orb being chased by a jet along with se...,9/24/2012,35.7211,-77.915833
80303,9/9/2012 20:10,elmont,ny,us,circle,600,10 minutes,Orange lights seen in Elmont&#44 Long Island&#...,9/24/2012,40.7008,-73.713333
80304,9/9/2012 20:30,mt. juliet,tn,us,light,120,2 minutes,Bright white light moving slowly across sky wi...,9/24/2012,36.2,-86.518611
80305,9/9/2012 20:30,ventura,ca,us,chevron,900,15 minutes,Beautiful bright blue delta shaped aerobatics.,9/24/2012,34.2783,-119.292222
80306,9/9/2012 20:52,south jordan,ut,us,circle,10,10 seconds,Circular disk with blinking lights scares two ...,9/24/2012,40.5622,-111.928889
80307,9/9/2012 21:00,elkhart,in,us,oval,600,10 minutes,It was the night of sept 9 between 9 and 10 pm...,9/24/2012,41.6819,-85.976667
80308,9/9/2012 21:00,new york city (brooklyn),ny,us,light,1290,21:30,Glowing&#44 circular lights visible in the clo...,9/24/2012,40.7142,-74.006389
80309,9/9/2012 21:00,pawleys island,sc,us,oval,60,less than a minute,One large bright orange flanked by three small...,9/24/2012,33.4331,-79.121667
80310,9/9/2012 21:00,ventura,ca,us,circle,300,5 minutes,Bright Blue Object seen floating in sky near C...,9/24/2012,34.2783,-119.292222
80311,9/9/2012 21:55,charleston,sc,us,flash,900,15 minutes,Orb of light flashing reds and blues&#44 stati...,9/24/2012,32.7764,-79.931111
80312,9/9/2012 23:00,gainesville,ga,us,light,5,5 seconds,Ball of light,9/24/2012,34.2978,-83.824167
80313,9/9/2013 0:15,norfolk,va,us,unknown,1,split second,Two or three lights shoot across sky over nava...,9/30/2013,36.8467,-76.285556
80314,9/9/2013 1:50,buffalo (west of; on highway 90 west),ny,us,triangle,180,3 minutes,Massive Flat Black triangle with 3 red lights.,9/30/2013,42.8864,-78.878611
80315,9/9/2013 3:00,struthers,oh,us,unknown,120,2 minutes,I saw a routaing line of stares that seemed to...,9/9/2013,41.0525,-80.608056
80316,9/9/2013 9:51,san diego,ca,us,light,4,~4 seconds,2 white lights zig-zag over Qualcomm Stadium (...,9/30/2013,32.7153,-117.156389
80317,9/9/2013 12:34,cedar park,tx,us,cigar,8,5-8 seconds,Cigar Shaped Object Descending in the Directio...,9/9/2013,30.505,-97.820000
80320,9/9/2013 20:20,tuscaloosa,al,us,fireball,60,1:00,White/green object much larger than &quot;shoo...,9/30/2013,33.2097,-87.569167
80321,9/9/2013 20:21,clarksville,tn,us,fireball,3,3 seconds,Green fireball like object shooting across the...,9/30/2013,36.5297,-87.359444
80323,9/9/2013 21:00,gainesville,fl,us,triangle,60,1 minute,Three lights in the sky that didn&#39t look li...,9/30/2013,29.6514,-82.325000
80326,9/9/2013 21:00,woodstock,ga,us,sphere,20,20 seconds,Driving 575 at 21:00 hrs saw a white and green...,9/30/2013,34.1014,-84.519444
80327,9/9/2013 21:15,nashville,tn,us,light,600,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.1658,-86.784444
80328,9/9/2013 22:00,boise,id,us,circle,1200,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.6136,-116.202500
80329,9/9/2013 22:00,napa,ca,us,other,1200,hour,Napa UFO&#44,9/30/2013,38.2972,-122.284444
80330,9/9/2013 22:20,vienna,va,us,circle,5,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.9011,-77.265556
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.6528,-97.477778

In [6]:
# Count how many sightings have occured within each state
state_counts = usa_ufo_df["state"].value_counts()
state_counts

ca    8683
fl    3754
wa    3707
tx    3398
ny    2915
il    2447
az    2362
pa    2319
oh    2251
mi    1781
nc    1722
or    1667
mo    1431
co    1385
in    1268
va    1248
ma    1238
nj    1236
ga    1235
wi    1205
tn    1091
mn     996
sc     986
ct     865
ky     843
md     818
nv     778
ok     714
nm     693
ia     669
al     629
ut     611
ks     599
ar     578
la     547
me     544
id     508
nh     482
mt     460
wv     438
ne     373
ms     368
ak     311
hi     257
vt     254
ri     224
sd     177
wy     169
de     165
nd     123
pr      24
dc       7
Name: state, dtype: int64

In [7]:
# Convert the state_counts Series into a DataFrame
state_ufo_counts_df = pd.DataFrame(state_counts)
state_ufo_counts_df.head()

    state
ca   8683
fl   3754
wa   3707
tx   3398
ny   2915

In [8]:
# Convert the column name into "Sum of Sightings"
state_ufo_counts_df = state_ufo_counts_df.rename(
    columns={"state": "Sum of Sightings"})
state_ufo_counts_df.head()

    Sum of Sightings
ca              8683
fl              3754
wa              3707
tx              3398
ny              2915

In [9]:
# Want to add up the seconds UFOs are seen? There is a problem
# Problem can be seen by examining datatypes within the DataFrame
usa_ufo_df.dtypes

datetime                 object
city                     object
state                    object
country                  object
shape                    object
duration (seconds)       object
duration (hours/min)     object
comments                 object
date posted              object
latitude                 object
longitude               float64
dtype: object

In [10]:
# Using to_numeric() to convert a column's data into floats
usa_ufo_df["duration (seconds)"] = pd.to_numeric(
    usa_ufo_df["duration (seconds)"])
usa_ufo_df.dtypes

/Users/Ronessa/anaconda/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

datetime                 object
city                     object
state                    object
country                  object
shape                    object
duration (seconds)      float64
duration (hours/min)     object
comments                 object
date posted              object
latitude                 object
longitude               float64
dtype: object

In [11]:
# Now it is possible to find the sum of seconds
usa_ufo_df["duration (seconds)"].sum()

351281285.38